server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
  config:
    import: optional:configserver:${CONFIG_URI}
#  security:
#    user:
#      name: from Config Server: Vault
#      password: from Config Server: Vault

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false